name: PerWorldChat
main: PerWorldChat\PerWorldChat
version: 2.0
api: 4.0.0
load: STARTUP
author: EvolSoft #edited by Henry
description: Set a separate chat for each world
website: https://github.com/Henry12960
